#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Listas de Paquetes para la Instalación
# -----------------------------------------------------------------------------
# Este archivo centraliza todos los paquetes que el script 'install.sh' puede
# instalar. Modifica estas listas para personalizar tu instalación.
# -----------------------------------------------------------------------------

# --- Paquetes Base Esenciales ---
# Fundamentales para que el script y el sistema base funcionen correctamente.
base_pkgs=(
  git
  curl
  ca-certificates
  base-devel # Necesario para construir paquetes de AUR
)

# --- Shell y Herramientas de Terminal ---
# Zsh, Oh My Zsh, zoxide, etc.
shell_pkgs=(
  zsh
  zoxide
  lazygit
  yazi
)

aur_shell_pkgs=(
  oh-my-zsh-git
)

# --- Herramientas de Desarrollo ---
# Paquetes de repositorios oficiales para desarrollo de software.
dev_pkgs=(
  aws-cli-v2
  nodejs # Requerido por Neovim y otros
  npm    # Requerido por Neovim y otros
)

# --- Paquetes de Desarrollo (AUR) ---
# Herramientas de desarrollo que se encuentran en el AUR.
aur_dev_pkgs=(
  mongodb-compass-bin
  postman-bin
  gitflow-avh
)

# --- Neovim y Dependencias ---
# Neovim y todas las dependencias necesarias para la configuración.
neovim_pkgs=(
  neovim
  ripgrep
  fd
  unzip
  fzf
  gcc
  make
  python-pynvim
  lua-language-server
  stylua
)

# --- Aplicaciones de Productividad y Medios ---
# Navegadores, ofimática, música, etc.
app_pkgs=(
  zathura
  zathura-pdf-mupdf
  pipewire-pulse
  pavucontrol-qt
  qt5ct
  qt6ct
  kvantum
  swww
  waybar
  kitty
  fuzzel
  wl-clipboard
  cliphist
  hyprlock
  slurp
  grim
  hypridle
)

# --- Aplicaciones (AUR) ---
aur_app_pkgs=(
  zen-browser-bin
  obsidian
  notion-app-enhanced
  spotify
  hyprshot-git
  satty
)

# --- Ofimática ---
# LibreOffice y paquetes de idioma/corrección.
office_pkgs=(
  libreoffice-fresh
  libreoffice-fresh-es
  hunspell-en_us
  hunspell-es_co
  hyphen-en
  hyphen-es
  mythes-en
  mythes-es
)

# --- Fuentes ---
# Fuentes de repositorios oficiales para UI y emojis.
font_pkgs=(
  noto-fonts
  noto-fonts-emoji
  ttf-firacode-nerd
  ttf-cascadia-code-nerd
  ttf-iosevka-nerd
  ttf-sourcecodepro-nerd
  ttf-ubuntu-mono-nerd
  ttf-jetbrains-mono-nerd
  ttf-hack-nerd
)

# --- Fuentes (AUR) ---
# Colección de Nerd Fonts y fuentes de compatibilidad (Microsoft).
aur_fonts_pkgs=(
  ttf-ms-fonts
)
