# Rules for applications

# windowrule = float,pavucontrol-qt
windowrule = float, class:^(pavucontrol-qt)$
windowrule = size 500 300, class:^(pavucontrol-qt)$
windowrule = move 55% 5%, class:^(pavucontrol-qt)$

# Satty
windowrule = float,class:^(satty)$
windowrule = center,class:^(satty)$
windowrule = size 80% 80%,class:^(satty)$

# Floating terminal for calcurse
windowrule = float,class:^(floating-terminal)$
windowrule = size 800 600,class:^(floating-terminal)$
windowrule = move 35% 5%, class:^(floating-terminal)$
