# Rules for applications

# windowrule = float,pavucontrol-qt
windowrule = float, class:^(pavucontrol-qt)$
windowrule = size 500 300, class:^(pavucontrol-qt)$
windowrule = move 55% 5%, class:^(pavucontrol-qt)$
