# Rules for applications

# windowrule = float,pavucontrol-qt
windowrule = float, class:^(pavucontrol-qt)$
windowrule = size 500 300, class:^(pavucontrol-qt)$
windowrule = move 100%-w-90 5%, class:^(pavucontrol-qt)$

# Satty
windowrule = float,class:^(satty)$
windowrule = center,class:^(satty)$
windowrule = size 900 900,class:^(satty)$

# Floating terminal for calcurse
windowrule = float,class:^(floating-terminal)$
windowrule = size 600 600,class:^(floating-terminal)$
windowrule = move 100%-w-20 5%, class:^(floating-terminal)$

# Blueman Manager
windowrule = float,class:^(blueman-manager)$
windowrule = size 400 300,class:^(blueman-manager)$
windowrule = move 100%-w-80 5%,class:^(blueman-manager)$

