# --- shell --- 

shell zsh

# --- Font ---
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14.0

# --- Window ---
window_padding_width 3

# --- Bell ---
enable_audio_bell no

# --- Cursor ---
cursor_shape beam
cursor_beam_thickness 1.5
cursor_trail 1

# --- Kanagawa Colors ---
background #1F1F28
foreground #C8C093
cursor #98BB6C
selection_background #223249
selection_foreground #C8C093

# Black
color0 #16161D
color8 #54546B

# Red
color1 #C34043
color9 #FF9E64

# Green
color2 #87A98A
color10 #98BB6C

# Yellow
color3 #D7827E
color11 #EBCB8B

# Blue
color4 #6A95AE
color12 #7E9CD8

# Magenta
color5 #957FB8
color13 #B85E80

# Cyan
color6 #2D4F67
color14 #5D7A8C

# White
color7 #C8C093
color15 #C8C093
